version: '3.3'

services:
  backend:
    build:
      context: ./backend
    volumes:
    - ./backend/:/opt/app
    ports:
    - "3333:3333"
    expose:
    - "3333"

  frontend:
    build:
      context: ./frontend
    volumes:
    - ./frontend/:/opt/app
    ports:
    - "8080:8080"
    expose:
    - "8080"


  mysql:
    build:
      context: ./mysql
      args:
      - MYSQL_DATABASE=default_database
      - MYSQL_USER=default_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    volumes:
    - ./data/mysql/:/var/lib/mysql
    ports:
    - "3306:3306"
    expose:
    - "3306"

  nginx:
    build:
      context: ./nginx
      args:
      - WEB_SSL=false
      - SELF_SIGNED=true
      - NO_DEFAULT=true
    volumes:
    - ./data/logs/nginx/:/var/log/nginx
    - ./certbot/certs/:/var/certs
    ports:
    - "80:80"
    - "443:443"
    tty: true

  certbot:
    build:
      context: ./certbot
    links:
    - nginx
    volumes:
    - ./certbot/letsencrypt/:/var/www/letsencrypt
    - ./certbot/certs/:/var/certs
