version: '3.3'

services:
  backend:
    build:
      context: ./backend
    volumes:
    - ./backend/:/opt/app
    depends_on:
    - mysql
    restart: always
    ports:
    - "3333:3333"
    expose:
    - "3333"

  frontend:
    build:
      context: ./frontend
    volumes:
    - ./frontend/:/opt/app
    ports:
    - "8080:8080"
    expose:
    - "8080"

  admin:
    build:
      context: ./admin
    volumes:
    - ./admin/:/opt/app
    ports:
    - "8000:8000"
    expose:
    - "8000"

  nginx:
    build:
      context: ./nginx
      args:
      - WEB_SSL=true
      - SELF_SIGNED=true
      - NO_DEFAULT=true
    volumes:
    - ./data/logs/nginx/:/var/log/nginx
    - ./certbot/certs/:/var/certs
    ports:
    - "80:80"
    - "443:443"
    tty: true

  mysql:
    build:
      context: ./mysql
    volumes:
    - ./data/mysql/:/var/lib/mysql
    ports:
    - "3306:3306"
    expose:
    - "3306"

#  certbot:
#    environment:
#    - CN=partymaker.zp.ua
#    - EMAIL=kostyk.pavel.09@gmail.com
#
#    build:
#      context: ./certbot
#    links:
#    - nginx
#    volumes:
#    - ./certbot/letsencrypt/:/var/www/letsencrypt
#    - ./certbot/certs/:/var/certs
